Add uikit properties parsing
design-ops/sketch-to-swiftUI pull request #20
Opened 2020-09-02 09:43 UTC by kerrmarin

Counterpart to https://github.com/design-ops/stylable-swiftui/pull/32

2020-09-07 21:46 UTC, kerrmarin commented
@atomoil ping

2020-09-07 22:50 UTC, atomoil requested changes

2020-09-07 22:50 UTC, atomoil commented on lib/processLayerStyles.js
> +        // Get properties
What properties?

2020-09-07 22:50 UTC, atomoil commented on lib/processLayerStyles.js
>  const layerFill = (layerStyle, outputFolder, sketchFile) => {
If this is now handling fill and shadow then it should named appropriately

2020-09-07 22:50 UTC, atomoil commented on lib/processLayerStyles.js
> +    let properties = []
This should be clearer - is styles == swiftUI and properties == UIKit ? If so, name them to be clearer

2020-09-07 22:50 UTC, atomoil commented on lib/processTextStyles.js
> +            `.kerning(${encodedAttributes.kerning})`,
Is kerning always present?

2020-09-07 22:50 UTC, atomoil commented on lib/processTextStyles.js
> +            `.font(UIFont(name: "${fontAttributes.name}", size: ${fontAttributes.size})!)` // using ! to unwrap the font. Should we do this? IMHO the font not being there is a programmer error
This should follow the name / value pattern of the SwiftUI for consistency, unless there’s a good reason not to :-)

2020-09-10 07:53 UTC, kerrmarin commented
@atomoil I've (I think) addressed all your points

2020-09-10 10:50 UTC, atomoil commented on lib/processLayerStyles.js
> +          properties: layerFillProperty(layerStyle)
```suggestion
          properties: layerFillUIKitBackground(layerStyle)
```
?

2020-09-10 10:51 UTC, atomoil commented on lib/processTextStyles.js
> +            // using ! to unwrap the font. Should we do this? IMHO the font not being there is a programmer error
can't you use `addOptionalProperty` ?

2020-09-10 10:51 UTC, atomoil commented on lib/processTextStyles.js
> +            // using ! to unwrap the font. Should we do this? IMHO the font not being there is a programmer error
oh, sorry, re-read and now understand the comment is for swift, not convertor

2020-09-10 10:54 UTC, atomoil commented on lib/processTextStyles.js
> +            { name: "textColor", value: `UIColor(red: ${color.red}, green: ${color.green}, blue: ${color.blue}, alpha: ${color.alpha})`},
can these properties move into functions, instead of being explicitly declared here?

2020-09-10 10:55 UTC, atomoil commented on lib/processTextStyles.js
> +            { name: "textColor", value: `UIColor(red: ${color.red}, green: ${color.green}, blue: ${color.blue}, alpha: ${color.alpha})`},
```suggestion
            { name: "textColor", value: getUIColor(color)},
```

2020-09-10 10:56 UTC, atomoil commented
Did you mean to remove kerning from the UIKit side?

2020-09-16 20:38 UTC, kerrmarin commented
@atomoil updated 👍 

I didn't remove the ker(r)nin, I just moved it to being optional; so I'm checking if it's there and if it is i'll add it.

2020-09-22 10:23 UTC, kerrmarin commented
@atomoil ping

2020-09-23 14:13 UTC, atomoil approved these changes

2020-09-23 15:16 UTC, merged