Add support for extracting themes
design-ops/sketch-to-swiftUI pull request #49
Opened 2021-07-16 09:23 UTC by kerrmarin

2021-10-04 10:21 UTC, kerrmarin-lvmh commented
ping

2021-10-31 22:56 UTC, kerrmarin commented
@atomoil ping

2021-11-01 17:57 UTC, atomoil requested changes

2021-11-01 17:57 UTC, atomoil commented on lib/template.hb.swift
> +{{#if theming}}
It _looks_ like theming is always set, if so this is unnecessary.

2022-02-17 08:03 UTC, merged